repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
      - id: ruff-format
        args:
          - --quiet
