from .util import (
    skip_if_unchanged,
)

skip_if_unchanged(__file__)


# def test_load():
#     assert_loads_correctly(
#         AuraSRArch(),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=32,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=32,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 64, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 256, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 3},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 32),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 16, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 8, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 4, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(2, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             down_dim_mults=(8, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             down_dim_mults=(4, 16, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             down_dim_mults=(4, 8, 32),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             down_dim_mults=(4, 8, 16, 32),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=4,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             full_attn=(False, False, False, True, False),
#             attn_depths=(2, 2, 2, 2, 2),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             full_attn=(False, False, False, False, True),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             full_attn=(False, False, True, True, True),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             full_attn=(False, True, False, True, True),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             full_attn=(True, False, False, True, True),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             self_attn_dim_head=32,
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             attn_depths=(2, 2, 2, 6, 4),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             attn_depths=(2, 2, 2, 2, 6),
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             mid_attn_depth=3,
#         ),
#         lambda: AuraSR(
#             dim=64,
#             init_dim=64,
#             channels=3,
#             image_size=None,
#             input_image_size=None,
#             skip_connect_scale=0.4,
#             style_network={"dim_in": 128, "dim_out": 512, "depth": 4},
#             up_dim_mults=(1, 2, 4, 8, 16),
#             num_conv_kernels=3,
#         ),
#     )


# def test_AuraSR_v1(snapshot):
#     file = ModelFile.from_url(
#         url="https://huggingface.co/fal/AuraSR/resolve/main/model.safetensors?download=true",
#         name="AuraSRv1.safetensors",
#     )
#     model = file.load_model()
#     assert model == snapshot(exclude=disallowed_props)
#     assert isinstance(model.model, AuraSR)
#     assert_image_inference(
#         file,
#         model,
#         [TestImage.SR_16, TestImage.SR_32, TestImage.SR_64],
#     )
