# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the workflow will run
on:
    pull_request:
        branches: ['*']
        types:
            - opened
            - synchronize
            - closed
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
                  cache: 'pip'
            - uses: pre-commit/action@v3.0.0
              env:
                RUFF_OUTPUT_FORMAT: github

    pyright:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
                  cache: 'pip'
            - run: pip install .[typecheck,test] --extra-index-url https://download.pytorch.org/whl/cpu
            - run: pyright src/
            - run: pyright tests/
            - run: pyright scripts/
